### PR TITLE
Complete schema.

### PR DESCRIPTION
**Pull request by trivialfis**
Hi @hcho3 , although this is WIP and quite early, but you are welcomed to comment on the PR if you have the time.  I'm bad at writing ( isn't that obvious? ) :) , I haven't read the conversation in previous PRs and issues thoroughly so some suggestions might be missing.  Will continue working on it. with a few more days I should be able to make it into shape.

The org file can be easily transformed into rst later, it's just easier for me to edit it.

### CODE REVIEW

**Comment by trivialfis** [comment]
Just click `view file` should get you a normal GitHub style document, no need to read the diff view.

**Comment by trivialfis** [comment]
@hcho3 The basic structure is here:

-top-level.org
-- linear-model.org
-- tree-model.org
-- objective
-- implementation-details.org

And enjoy your holiday. :)

**Comment by trivialfis** [comment]
@hcho3 I'm not sure about how to save tree nodes with adj-list.  I like that idea, but how do we recover the parent field efficiently?

**Comment by trivialfis** [comment]
Okay, I think the adjacent list is doable.  I will try to give a draft implementation after this PR.

**Comment by hcho3** [comment]
The adjacency list is included in the latest version of schema.

**Comment by trivialfis** [comment]
@hcho3 I added some changes to the schema.  I think there will be something I miss and I'm not sure how do you want it carry this out.  Can you layout some details of your plan when time allows?
For examples:
 - Do you want to implement your initial schema first now that we have two schemas?
 - If I start the initial implementation, will there be duplicated work?
 - What's your idea about utilizing adj-list, it's a representation of graph with each node pointing to each other by an index field, how should those meta data like `leaf_output` be saved?

And I'm looking forward to your comments since I'm working blindly.  I hope that we can talk about each object one by one at some point so that we can have a common knowledge about how the complete schema should look like.

Please let me know when do you want to come back for this.  I don't have Christmas so you don't need to consider my time schedule. :)

**Comment by hcho3** [comment]
@trivialfis I think it's best to merge your suggestion into the JSON schema before implementing it. This is so that we don't duplicate work. I'll look over the proposal first.

**Comment by trivialfis** [comment]
@hcho3 Let me know when you are ready. :)

**Comment by hcho3** [comment]
See #6

**Pull request closed without merging**
